Fix cmake Dockerfile issue on Linux (#17416)
* Fix cmake Dockerfile issue on Linux

When running cmake on Linux with (clean build with no cached docker images):
```
tensorflow/tools/ci_build/ci_build.sh CMAKE tensorflow/tools/ci_build/builds/cmake.sh
```

The following isse was encountered:
```
Step 11/13 : RUN pip install --upgrade termcolor
 ---> Running in 838167596eb6
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz
  ......
  ......
  ......
  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for termcolor
```

This fix adds the missing `pip install wheel`

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Update golang installation in cmake Dockerfile

This fix updates the golang installation in cmake Dockerfile.
Previously, `ppa:ubuntu-lxc/lxd-stable` was used but it has been
deprecated, see:
http://lxc-users.linuxcontainers.narkive.com/IlHLLHqN/lxd-official-ppa-deprecation

That caused the following error:
```
Step 13/14 : RUN add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
 ---> Running in 09301ba43a33
Cannot add PPA: 'ppa:~ubuntu-lxc/ubuntu/lxd-stable'.
The team named '~ubuntu-lxc' has no PPA named 'ubuntu/lxd-stable'
Please choose from the following available PPAs:
 * 'buildd-backports':  linuxcontainers.org: buildd backports
 * 'daily':  linuxcontainers.org: development builds
 ......
 ......
```

This fix updates the golang installation and use backported xenial (16.04),
as was suggested in the link:
http://lxc-users.linuxcontainers.narkive.com/IlHLLHqN/lxd-official-ppa-deprecation

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>