[OpenCL] Fixes linking issue
c13cb2e5777852c6a498410669b24ac346114eba introduced linking issue that caused

logging.cc:(.text+0xa64): undefined reference to
`tensorflow::StringPiece::Hasher::operator()(tensorflow::StringPiece) const'