Change behavior of tf.layers._Layer: scope (if not provided) is set lazily.
Also fixes #8504.

This doesn't affect any existing users (no one is using the OO api yet).
However is necessary for compatibility with RNNCell; and the behavior has
been somewhat ambiguous up until now.  Defines a behavior and adds unit tests
to make it clear.

The original behavior of _Layer is to immediately create the variable scope
it will use, in its initializer.  However, this doesn't work with _reuse=True,
and may not be the right behavior in general.

With RNNCells' current design the internal scope is set lazily based on the
first __call__ into the layer.  This allows one to write:

cell_fw = LSTMCell(...)
cell_bw = LSTMCell(...)
... = tf.nn.dynamic_bidirectional_rnn(cell_fw, cell_bw, ...)

then cell_fw gets the variable scope '.../bidirectional_rnn/fw/lstm_cell' and
cell_bw gets the variable scope '.../bidirectional_rnn/bw/lstm_cell'; thus their
variable names are tied to their function.

Furthermore, this change allows Layers constructed with reuse=True to reuse
the scopes within which they are **called** the first time.  Before this,
a new scope was always created, and having reuse=True would just lead to
errors (see, e.g., github issue #8504).

with tf.variable_scope('new_scope'):
    ker = tf.get_variable('kernel', [5, 6])
    tf.layers.dense(inputs=tf.constant(np.random.randn(3, 4, 5)), units=3, reuse=True)

used to raise:

ValueError: Variable new_scope/dense/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

The new (correct) behavior is to reuse the 'kernel' variable in scope 'new_scope'.

I have additionally added an optional argument scope= to the __call__ method
to provide a way to provide a scope upon application.  This scope is used
only if the layer has not yet been built and no scope has yet been provided.

Added unit tests to show the behavior.
Change: 150701086