Revert "Add synthetic datasets (#5315)"
This reverts commit 2b8a5f5e558617097f82517acf3ffda073545433.

Reason for rollback: Broke builds due to errors such as:

File
"/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py",
line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import synthetic
    ImportError: cannot import name synthetic