Simplify Eigen package config (#3288)
* Simplify Eigen package config

* Add missing unsupported/Eigen/*

* Fix pip setup.py

* Adjust new eigen header

* Fix bazel include dependency error

* Adjust Makefile to work with Eigen changes

* Remove nvcc workaround for CUDA <= 6.0

CUDA versions prior to 6.5 gave an

    error: kernel launches from templates are not allowed in system files

error when using gcc v4.8 and including code that uses templated
kernel launches via `-isystem`.
In order to work around this, the GPU crosstool converted `-isystem`
arguments containing the cuda headers into `-iquote` arguments.
This workaround has now been removed.

* Configure cmake and make to get eigen version from tensorflow/workspace.bzl